protocol: http  # http or https
host: ip:port   # listen on where, such as 127.0.0.1:8001
domain: domain  # your domain, such as github.com. you can also set it the same as host
mysql: mysql//user:password@(host:port)/database?charset=utf8&parseTime=True&loc=Local # mysql client
redis: 127.0.0.1:6379//password  # redis client
gkey: your_site_client_key       # you key of google re captcha
gsecret: your_site_server_key    # you secret of google re captcha